docs/en/index.md
=> fix: add index page for en

src/emd/cli.py
=> fix: helper title

README.md
=> docs: fix install cli

pyproject.toml, src/pipeline/backend/backend.py, src/pipeline/backend/huggingface/llm/transformer_llm_backend.py, src/pipeline/utils/common.py
=> fix: bugs in huggingface engine

src/emd/sdk/clients/ecs_client.py, src/emd/utils/framework_utils.py, src/pipeline/framework/fast_api/fast_api.py
Add model id and model tag to all FastAPI endpoint.
=> fix: add model id and model tag to all fastapi endpoint.

pyproject.toml, src/emd/models/engines.py, src/emd/models/model.py, src/pipeline/backend/backend.py, src/pipeline/backend/convert_engine_image_to_dmaa_dockerfiles/baichuan_m1_vllm_image_build.md, src/pipeline/backend/huggingface/llm/transformer_llm_backend.py, src/pipeline/utils/common.py
=> feat: support baichuan m1

.github/workflows/build-package.yml
=> fix: update workflow build action

src/emd/cfn/codepipeline/template.yaml, src/emd/cfn/ecs/post_build.py
=> fix: handel update stack error

.github/workflows/build-package.yml
=> chore: simple run emd after build

src/emd/cfn/ecs/cluster.yaml, src/emd/cfn/ecs/template.yaml, src/emd/cfn/sagemaker/template.yaml, src/emd/cfn/sagemaker_async/template.yaml, src/emd/cfn/vpc/template.yaml, src/emd/cli.py, src/emd/commands/deploy.py, src/emd/commands/version.py, src/emd/sdk/destroy.py
=> fix:fix cli bugs

src/emd/cfn/codepipeline/template.yaml
=> fix: update code build queue to parallel

.github/workflows/release-package.yml, src/emd/revision.py
=>  chore: add release pipeline

.github/workflows/release-package.yml
=> fix: update toml in workflow

.github/workflows/release-package.yml
=> fix: package issue

.github/workflows/release-package.yml, README.md
=> fix: update readme with cli usage

src/emd/cfn/codepipeline/template.yaml
=> fix: fix pipeline mode to QUEUED

README.md
=> doc: update animate format

README.md
=> chore: update readme for installation

src/emd/sdk/invoke/invoker_base.py
=> fix: add region support for invoke client

src/emd/sdk/clients/ecs_client.py, src/emd/sdk/invoke/conversation_invoker.py, src/emd/sdk/invoke/invoker_base.py
=> fix: ecs client invoke issue

src/emd/cfn/codepipeline/template.yaml, src/emd/sdk/bootstrap.py
=> fix: handel code build exceptions

src/emd/commands/invoke/invoke.py, src/emd/sdk/clients/ecs_client.py, src/emd/sdk/invoke/conversation_invoker.py
=> fix: support stream for llms

src/emd/models/custom/custom_docker.py
=> fix: support more instance type for custom

src/emd/cfn/shared/openai_router/go.mod
=> fix: fix go mod

src/emd/cfn/codepipeline/template.yaml, src/emd/cfn/ecs/template.yaml, src/emd/cfn/shared/ecs_cluster.yaml
=> fix: fix ecs build templates

src/emd/cfn/ecs/template.yaml, src/emd/cfn/shared/ecs_cluster.yaml
=> fix: update custom resource name for api router deployment handler

src/emd/cfn/shared/ecs_cluster.yaml
=> fix: custom resources function

src/emd/cfn/ecs/template.yaml
=> fix: fixed connect timeout for default time

src/emd/cli.py, src/emd/commands/example.py, src/emd/commands/models.py, src/emd/commands/status.py
=> fix: update user experience

src/emd/cfn/ecs/template.yaml, src/emd/models/utils/serialize_utils.py
=> fix: ecs rule in target group

src/emd/constants.py
=> fix: fix local deployment path

src/emd/commands/deploy.py, src/emd/models/services.py
=> fix: update deployment prompts and messages

docs/en/installation.md
=> docs: update installation.md

docs/en/sdk_api.md, docs/mkdocs.en.yml
=> doc: add SDK API doc

src/emd/models/embeddings/qwen.py, src/emd/models/engines.py, src/emd/models/model_series.py, src/emd/models/utils/constants.py
=> feat: add gme-Qwen2-VL-7B-Instruct

src/emd/models/embeddings/__init__.py, src/emd/models/embeddings/bge_vl.py, src/pipeline/backend/huggingface/embedding/transformers_embedding_backend.py
=> fix: multimodal embeddings (text + image)

src/pipeline/framework/fast_api/fast_api.py
=> fix: fixed invocation path in fastapi

.github/workflows/generate-model-config.yml, docs/en/index.md, docs/en/model-generator.html, tests/generate_model_config.py
=> fix: development build

docs/mkdocs.en.yml
=> doc: update index for model list

src/emd/models/llms/qwen.py
* Qwen/Qwen3-30B-A3B-Instruct-2507
=> feat: Qwen/Qwen3-30B-A3B-Instruct-2507 and Qwen/Qwen3-30B-A3B-Thinking-2507

docs/en/model-generator.html, src/emd/models/embeddings/bge_vl.py
1. add `g5dxlarge_instance` for` bge-vl-large`
=> feat: add g5dxlarge_instance for bge-vl-large
